client:
  account_tag: client
  tunnel_id: cac95849-84df-490c-9958-e150e1b0b266
  tunnel_secret: eyJhIjoiYzQ4M2YzZWI4NDlhZDdlZDQyYjk4ODljYWY2MmYxMjciLCJ0IjoiY2FjOTU4NDktODRkZi00OTBjLTk5NTgtZTE1MGUxYjBiMjY2IiwicyI6Ik5UZGxOemhoTkRZdE5UTTNaaTAwTkdGaUxUazNNakF0WWpjek9XRTJaV0l3TXpSayJ9

endpoint:
  connector_id: 0e534f90-9255-410d-8873-42451882e1ad
  connector_port: 8050
