services:
  app:
    image: cfapp
    hostname: server
    networks:
      - docker-net
    restart: always
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yaml run
    volumes:
      - ./config:/etc/cloudflared
    networks:
      - docker-net
    restart: always

networks:
  docker-net: